[platformio]
default_envs = esp32s3-devkitc-1

[env:esp32s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_ldf_mode = deep+
build_unflags =
  -std=gnu++11
build_flags =
  -std=gnu++17
  -D USER_SETUP_LOADED
  -D TFT_WIDTH=480
  -D TFT_HEIGHT=320
  -include include/TFT_Setup.h
lib_deps =
  adafruit/Adafruit ADS1X15@^2.5.0
  adafruit/RTClib@^2.1.4
  bodmer/TFT_eSPI@^2.5.43
  knolleary/PubSubClient@^2.8
